{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge.gradle",
    "module": "ForgeGradle",
    "version": "6.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.41.jar",
          "url": "ForgeGradle-6.0.41.jar",
          "size": 496801,
          "sha512": "0ef8ecb1c4bdc6a5f8eb32d72d20390fb01e0ccd0cd3f0051e3ee36152578d8247352f9d5eb1009b3da973ebfaec982daef506f7d3741b5862cf252311640015",
          "sha256": "0a06ee7f4a16c79840d45ba646a1901e9552a3751c83b9d14083b43fe0fd317d",
          "sha1": "0d098efda1c2f1e36a43e7cc8995482afcf69f43",
          "md5": "74b01d943a6d058bb0d0f6d85f1058d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.10"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.12"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-6.0.41.jar",
          "url": "ForgeGradle-6.0.41.jar",
          "size": 496801,
          "sha512": "0ef8ecb1c4bdc6a5f8eb32d72d20390fb01e0ccd0cd3f0051e3ee36152578d8247352f9d5eb1009b3da973ebfaec982daef506f7d3741b5862cf252311640015",
          "sha256": "0a06ee7f4a16c79840d45ba646a1901e9552a3751c83b9d14083b43fe0fd317d",
          "sha1": "0d098efda1c2f1e36a43e7cc8995482afcf69f43",
          "md5": "74b01d943a6d058bb0d0f6d85f1058d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.41-sources.jar",
          "url": "ForgeGradle-6.0.41-sources.jar",
          "size": 216909,
          "sha512": "e4fb4b29bc2e38d603aa3a71899b724b4388c21d448bce120caff61fa877b7e1eaf10dddaa0544d396665c6886974cb3fb0157906154332078aba18101f848a4",
          "sha256": "567fd3e6c7a1eac866ee71eac0b41842bb0790fb2394080c39430c5e2e7d7c99",
          "sha1": "476a24360519d4930aa71ba1f5a5902fb94cdc56",
          "md5": "cfebdf6ad350acd49db36e047699f1a0"
        }
      ]
    }
  ]
}
